### ISSUE TITLE
Is there a datepicker component that is compatible with react-intl?

### ISSUE THREAD

**Issue by box-turtle** [yahoo/react-intl#101]
Every datepicker component I can find relies on either moment.js or globalize.js but is seems redundant to have to include these. Is there a recommended datepicker control to use with react-intl?

**Comment by gpbl** [comment]
[I'm planning](https://github.com/gpbl/react-day-picker/issues/2) to make `react-day-picker` working without moment.js, and eventually rely on the `Intl` API (I'm shameless seeking for some help). Anyway, this is more related to `Intl` than `react-intl`. The use of external libraries is due to date calculations more than translating months and week names.

**Comment by caridy** [comment]
closing this one... but keeping the issue `unlocked` in case someone wants to share some links in the future.

**Comment by gpbl** [comment]
The `Intl` API does not say anything about the first day of the week, which is required for a day picker, hence the need to use external libraries...

**Comment by caridy** [comment]
@gpbl you can open a issue on https://github.com/tc39/ecma402, and we can try to push for some low-level primitive under `Intl` to provide such as information, seems useful.

**Comment by gpbl** [comment]
Thanks @caridy (welcome back!) 

I've added an issue here https://github.com/tc39/ecma402/issues/6
