### ISSUE TITLE
Component level i18n

### ISSUE THREAD

**Issue by slatkovic** [yahoo/react-intl#106]
Given that we have a component like this one...

```javascript

var Title = React.createClass({
    
    mixins: [IntlMixin],

    render: function() {
        return (
            <span>{this.getIntlMessage('title')}</span>
        );
    }
});

```

...is there a way to feed multiple locale groups into react-intl for that specific component...

```json
{
  "en-US": {
    "title": "Title"
  },
  "fr-FR": {
    "title": "Le Title"
  },
}
```

...and have react-intl resolve the proper message on render?

```json
React.render(
    <Title locales="fr-FR" />, //results in <span>Le Title</span>
    ...
);
```

**Comment by ericf** [comment]
I'm not sure I follow… can you provide some more details on what you're trying to do?

**Comment by slatkovic** [comment]
Sure. I am working on a framework/architecture for standalone, isolated React components. The idea is to encapsulate the behavior, stylesheets and locale content for each component. That way, components can be easily tested, shared, composed, etc. 

Historically, a single l10n file per locale was used since each file would contain localized content for the whole app. React components are small so it would make much more sense to use a single l10n file with different locale groups like above. 

I would also like to encapsulate the locale detection logic and detach that behavior from component logic. In other words, detect the locale, pass it to the high level App component and let it trickle down to other components from there. 

Hope this makes sense.

**Comment by ericf** [comment]
Okay, yeah this makes more sense now.

To start there are several threads related to what you're doing which you might find valuable.
See: https://github.com/yahoo/react-intl/issues/99#issuecomment-89922631 and https://github.com/yahoo/react-intl/issues/89.

Determine the locale once and feeding it in at the top level seems to be the way to go. This is supported today and is the pattern we encourage. We have some details on the site for how to determine the user's locale on the [server](http://formatjs.io/guides/runtime-environments/#user-locale-server) and on the [client](http://formatjs.io/guides/runtime-environments/#user-locale-client). Also the `IntlMixin` will trickle the `locales` property down through the `context`.

I'm also on-board with the idea of co-locating strings files with components instead of having one giant strings file for the app. I'm actively working on just this and I've arrived a few key insights:

An app will have a few different classes of React components. There will be some which are highly sharable and are used in many different contexts throughout the app, one such might be a `<Button>`. For these components, it doesn't make sense to co-locate strings, rather they should have `props` for strings to be passed-in. Let's call these "atoms".

There will be another set of components within your app that define the logical pieces, and implement your app's main "nouns". These components are likely doing firing Flux actions, and are building major chunks of the UI using the highly-sharable components/atoms. The major difference here we have a context for our UI and its strings that should be displayed. Let's call these "molecules".

I think the "molecules" class of components are the right level to co-locate strings because they have the context of some logic piece of the UI and define one of the app's "nouns". This context also provides translators with the information they need to translate a given string — especially when the same word in English translates to different words for different contexts.

I hope that helps. Let me know what you think.

**Comment by slatkovic** [comment]
Thanks, have more context now. I like the atom/molecule analogy, it really makes sense. It seems we're pretty much on the same page. Let me know if there's anything I can help with.

**Comment by caridy** [comment]
Can we close this one @slatkovic?

**Comment by dropfen** [comment]
Hmm, you can just provide your messages with the following example from the Root component:
```getChildContext() {
  return { messages: this.props.locale }
}```
and have it available for all Children and Grandchildren. ``getChildContext`` is not official yet, but it works ;)

**Comment by slatkovic** [comment]
@caridy sure, thanks all!
