### ISSUE TITLE
FormatMessage supporting array of dates in a single formatMessage?

### ISSUE THREAD

**Issue by SeamusY** [yahoo/react-intl#1143]
### Support a feature
If this is a FEATURE REQUEST, please:
Is there a feature where translation for the potential string like:
['Sunday', 'Monday','Tuesday'..etc]
As one single format text?

<FormatMessage id="something", description="array of days" defaultMessage="{translated:Sunday, translated:Monday, translated:Tuesday.etc}"

Is it possible?

**Comment by papasmile** [comment]
Hi, @SeamusY, is weekday your only use case?  What about:
```
let aDate = new Date(Date.parse('Fri, 22 June 2018 00:00:00'));
[...Array(7)].map(days => {
  aDate.setDate(aDate.getDate() + 1);
  return intl.formatDate(aDate, { weekday: 'long' });
}).join();
```

Or do you mean some kind of array notation?  What would go in translations file, then, since it's a string?  Maybe something like a template notation:
```
{
  'app.greeting': '{0|sunday in english}, {1|moday in english}, {2|tuesday in english}'
}
```
That sounds like other template issues logged e.g. #1131, #1138...

Perhaps another type of formatter for convenience is what you'd like?  If folks are interested you could contribute something e.g.
```
<FormattedMessageArray
    idArray=['app.greeting.sunday', 'app.greeting.monday', 'app.greeting.tuesday']
    defaultMessageArray=['Sunday','Monday','Tuesday']
    delimiter=", "
/>
```
Or just implement your own helper method like that (your linter may vary :):
```
const formatMessageArray = (idArray, defaultMessageArray, delimiter) => (
  idArray.map((anId, index) => <FormatMessage id="{anId}" defaultMessage="defaultMessageArray[index]" />).join(delimiter);
);
```

Hope that helps.

**Comment by SeamusY** [comment]
@papasmile thank you, i believe the only use case was probably the template issue as you posted. I will close this as it's similar to template issues already logged.
