### ISSUE TITLE
Please use spectrum.cha instead of Slack

### ISSUE THREAD

**Issue by steida** [yahoo/react-intl#1173]
One thing. Crawlable by Google.

Slack isn't really suited for OSS.

**Comment by sourabh2k15** [comment]
Although I like using slack this argument makes sense to me. I tried spectrum chat it's a bit different from slack and more like zulip-chat. Gitter is also used for OSS and it's totally like slack.                

That being said any chat (including slack) could be an overkill for now because the most useful discussions are happening on Github. I would like to know what other people think of this.

**Comment by papasmile** [comment]
@DragonRaider5 created a Slack channel for some informal chat and collaboration.  1) Any major chat platform would serve that purpose and doesn't need to be searchable at this point.  2) I'm much more concerned with keeping communication safe and clean: maybe you and redonkulus could get admin access for starters?

**Comment by DragonRaider5** [comment]
Hi,

I'll put it like this: In the end I'm happy as long as any chat platform is being used.
The discussion whether or not to use Slack might be a little bit over the top for now I think.

Also, as @papasmile mentioned: Slack was never meant to replace GitHub issues or something - it originally only was about quick Q&A and coordination for the new context API rewrite.

All of this being said: I think the key focus should be to get some communication going at all...
In the end I don't rly mind if it's Slack or not, as long as there's some collaboration going on.

**Comment by redonkulus** [comment]
You can continue the discussion, but I'm closing the issue. The slack link was added by the community, if everyone decides to use something else, I will gladly update the link.
