### ISSUE TITLE
Method to retreive messages in language that's not the current language?

### ISSUE THREAD

**Issue by yahu577** [yahoo/react-intl#147]
Is there any way to get message from the translation table that's not the current language? I have a use case that need this feature. e.g.
```
// current language is english
intl.getIntlMessage('messageKey', 'zh-hk');
```

**Comment by caridy** [comment]
Normally, you will only load the messages you need in the language you need. If you have an app that needs more than that, let's say you have an app that display info in multiple languages, then you should not rely on `getIntlMessage()`, you should implement your own abstraction to resolve messages. The resolution process we provide thru `getIntlMessage()` is very simple, and its mean to cover the 90+ percentile of the cases, instead of covering all cases.

**Comment by ericf** [comment]
@yahu577 can you describe your use case?

**Comment by yahu577** [comment]
@ericf, we are building a dashboard, which is multilingual, whereas it's also used to configure our application that is also multilingual. The list of configurations include CMS-like feature to manage multilingual content in the application. In that panel, we need to 'preview' the configuration and therefore needed to show application content in the locale that's different from dashboard's current language.

**Comment by ericf** [comment]
React Intl isn't really in the business of managing your application state — we think of translations as app state. But it's much clearer on how to do this in [v2](https://github.com/yahoo/react-intl/tree/v2-dev) with the new `<IntlProvider>` component, and if you're using some flux variant, you could store the translations in a store.

**Comment by ericf** [comment]
See: #162
