### ISSUE TITLE
FormattedRelative capitalization

### ISSUE THREAD

**Issue by janicduplessis** [yahoo/react-intl#163]
Is there a simple way to handle capitalization of relative dates inside a message?

For example the following messages would have different capitalization:

Created yesterday.
Yesterday at ...

I could use the API directly and handle the capitalization manually but I was hoping for a better way!

**Comment by ericf** [comment]
The capitalization is pulled directly from the ICU data, they do tweak these overtime to better match the colloquial way things are capitalized. The problem here is not knowing the full context of how the formatted relative date string is used to determine whether it's at the beginning of a sentence or not.

Can you describe more what you were hoping to be able to write so I can think about the use care more?

**Comment by janicduplessis** [comment]
It could be simply on the component level, I guess it would be possible to do it on the message level too (Does the ICU message format has any support for this?).

```jsx
<FormattedRelative value={date} capitalize />
```

or in the message

```
{formattedDate, capitalize} ...
```

In the context of the message it would even be possible to infer the capitalization by knowing where the variable is located in the message.

Anything that does not require manipulating the string directly would be great and fit a lot better with the way React components work.

**Comment by ericf** [comment]
So this gets much better in v2 with an improve API and function-as-child support for all `<Formatted*>` components: #162

**Comment by janicduplessis** [comment]
Yes, I was thinking of using something like this for now. The case isn't that common so it might be good enough :).

```
<FormattedRelative value={date}>{someUtilFunctionThatReturnsASpanCapitalized}</FormattedRelative>
```

**Comment by ericf** [comment]
:+1:

**Comment by ericf** [comment]
Closing this for now… if others stumble on this, adds your thoughts.
