### ISSUE TITLE
FormattedMessage omits parameter if 0

### ISSUE THREAD

**Issue by eschiebel** [yahoo/react-intl#240]
```
var c = 0;
<FormattedMessage message="{count} bananas" count={c}/>
```
renders only "bananas" if `c===0`, but will print "0 bananas" if `c==="0"`.

I think there's an `if(substitution_parameter_value)` in the code somewhere that's not taking 0 into account.

**Comment by ericf** [comment]
If you want to render a number, use `{count, number}`. This will make sure larger numbers, e.g. `100` get rendered with the correct thousands separators. Since you also have a label, you probably want to use: `{count, plural, one {# banana} other {# bananas}`

http://formatjs.io/guides/message-syntax/#simple-argument

**Comment by ericf** [comment]
https://github.com/yahoo/intl-messageformat/pull/112
