### ISSUE TITLE
FormattedRelative: "React checksum mismatch" because seconds difference.

### ISSUE THREAD

**Issue by 3den** [yahoo/react-intl#254]
Hi, the `<FormattedRelative />` component is very nice but currently it is giving me a "React checksum mismatch" when you refresh a page with changes that are less than a minute old. I looked at the code but I could not find an option to be more vague about the time, by returning "less than a minute ago" for everything that was posted in less than a minute, that would solve this error.

Below I am posting the exact error we get:

```
React checksum mismatch
(client) 81fda92-7b66-412e-8014-32e5ab4f8561-bylineSpan.0">6 seconds ago</span></span></div><div class="messa
(server) 81fda92-7b66-412e-8014-32e5ab4f8561-bylineSpan.0">4 seconds ago</span></span></div><div class="messa
```

**Comment by ericf** [comment]
This was addressed in [`2.0.0-beta-1`](https://github.com/yahoo/react-intl/releases/tag/v2.0.0-beta-1). `<IntlProvider>` has an `initialNow` prop which allows for the "now" time to be stable for the initial render on the client and server. By default, both `<FormattedRelative>` and `formatRelative()` access "now" via a function that the `<IntlProvider>` implements.

What you'll want to do is capture `Date.now()` before rendering the `<IntlProvider>` on the server and pass that value as its `initialNow` prop, serialize the same value to the client, and also pass it in to the `<IntlProvider>` when rendering on the client.

**Comment by 3den** [comment]
@ericf the error above was on `2.0.0-beta-1` because it shows "6 seconds ago". Is there a way to replace that with "less than a minute ago"?

**Comment by ericf** [comment]
Did you try using the `initialNow` prop on your `<IntlProvider>`? That solves the "4 seconds ago" vs. "6 seconds ago" problem.

There's no way to say "less than X", the data for all 200+ languages that are supported come from the CLDR, and React Intl uses this data directly. If you want to _always_ force it to display in "minutes" you can set `units` to `"minute"`. Otherwise, you'd have to localize "less than a minute ago" as a message and use `<FormattedMessage>`

**Comment by 3den** [comment]
nice thanks!
