### ISSUE TITLE
Missing currency sign: SGD

### ISSUE THREAD

**Issue by Moezalez** [yahoo/react-intl#273]
Singapore dollar (SGD) does not resolve to its sign: $.
https://en.wikipedia.org/wiki/Singapore_dollar

Not sure where to direct that issue. Here or formatjs?

**Comment by ericf** [comment]
Which browser?

**Comment by Moezalez** [comment]
Safari & Chrome, haven't tested it anywhere else

**Comment by ericf** [comment]
This is a Chrome bug, try this in Firefox and you'll see it's correct:
```js
new Intl.NumberFormat('en-SG', {style: 'currency', currency: 'SGD'}).format(1);
```

Chrome has a similar issue with INR: https://github.com/yahoo/react-intl/issues/231

**Comment by SavageWilliam** [comment]
@ericf 

instead of:
```
ar nf = Intl.NumberFormat(['en-sg'], {style:'currency', currency:'SGD', currencyDisplay:'symbol'});
```

What setup is required to use with 

```
<FormattedNumber
    value={value}
    style='currency'
    minimumFractionDigits={0}
    maximumFractionDigits={0}
    currency={'SGD'} />
```

**Comment by arvinsim** [comment]
I have the same issue. I still get `SGD` instead of `S$`

**Comment by orkunozekin** [comment]
A way around can be by manually inserting the SGD symbol as an exception to other currencies: 

`const formatCost = (cost, currency = "USD") => {
  let formatter = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency,
  })
  //because Intl.NumberFormat doesn't support SGD
  if (currency === 'SGD') {
    formatter = new Intl.NumberFormat('en-US', {
      style: 'decimal',
    })
    return 'S$' + formatter.format(Number(cost)) 
  }

  return formatter.format(Number(cost))
}`
