### ISSUE TITLE
Retrieving formatted month name?

### ISSUE THREAD

**Issue by m4nuC** [yahoo/react-intl#325]
How can I retrieve a month name according to current locale? The `FormattedDate` component doesn't seem to allow for this feature.

**Comment by ericf** [comment]
Set `month` to `"long"`. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Parameters

**Comment by m4nuC** [comment]
Thanks, but I mean how can I retrieve only the month name, without the year and day.

**Comment by ericf** [comment]
Your best bet is going to be to pull this information out of the CLDR directly. It never makes sense to format a date to a month because it's ambiguous and not colloquial. What's your reasoning for only wanting the month?

**Comment by m4nuC** [comment]
The use case is for a calendar. I need the current month to be displayed as a heading and the next and previous month names to be used as links to navigate the calendar. It would be great to be able to set the `year` and `day` props to `false` in order to achieve this.

**Comment by ericf** [comment]
You want the CLDR data, not the date formatting for this use case.

**Comment by m4nuC** [comment]
How does that work, is it possible to access CLDR data via react-intl.

**Comment by ericf** [comment]
It's not, we only extract out the data we need to support plural and relative time formatting. You can find out more about the CLDR's JSON data here: https://github.com/unicode-cldr/cldr-json

See: https://github.com/unicode-cldr/cldr-dates-full/blob/28.0.0/main/en/ca-gregorian.json#L14

**Comment by m4nuC** [comment]
Since this data is already available in intl, it make more sense in my app to get that data from one source. Maybe there could be a component for retrieving locale data? 

Otherwise setting `false` to the  some props on the `FormatDate component` would be great. I can imagine that sometime you would want to display a date without the year for instance. Would that feature make sense ?

**Comment by ericf** [comment]
You're making a calendar, using locale data from CLDR seems like the best approach. I provided links to the built in `Intl.DateTimeFormat()` API, as part of ECMA 402 what you're asking for isn't covered, because it doesn't make sense to format a date to only a month name — that's not formatting, that's simply data lookup.

The `<FormattedDate>` component calls into `Intl.DateTimeFormat()`, so there's no magic here, it's limited to what the API provides.

I've prosed a `formatToParts()` feature for ECMA 402, which will allow access to the month names, but still this isn't the right approach for what you want — I recommend extracting the data you need from CLDR.

**Comment by lauterry** [comment]
Hi 

In order to display only the month, I have set the day to 1 and the year to this year which give the following code :  

```
renderMonth(month) {
	if (month) {
		const thisYear = new Date().getFullYear();
		return <FormattedDate value={ new Date(thisYear, month - 1, 1) } month="long"/>;
	}
}
```

This method will then display only the month :) 

```
<div>{ this.renderMonth(8) }</div>
```

This is my workaround :)

Hope this helps

Best regards
