### ISSUE TITLE
Style output for currency?

### ISSUE THREAD

**Issue by wzup** [yahoo/react-intl#346]
Is there some probe-tested way to style output for currency? To avoid much hacking. 

An example. Please, pay attention to `&nbsp;` characters in a tag from a browser:
Locale: RU
Currency: IDR
Output: `300 000 IDR`
In a browser: `<span data-reactid=".0.$0.0.0.1.0">300&nbsp;000&nbsp;IDR</span>`

What I want is to style figures (`300 000`) and currency name (`IDR`) separately. I want to be able to embed them in `<span class="myStyles">`, for example. Something like this:
```
<span data-reactid=".0.$0.0.0.1.0">
   <span class="figures">300&nbsp;000</span>&nbsp;
   <span class="currency-name">IDR</span>
</span>
```

To get something like this:
![currency google chrome 2016-03-06 20 54 18](https://cloud.githubusercontent.com/assets/3880497/13554240/c52815ae-e3dd-11e5-956a-0409aeab56a3.png)

Is there some out-of-the box way to do so?

**Comment by ericf** [comment]
There isn't today because the `Intl` built-ins' `format()` method return opaque strings. But we have a [proposal](https://docs.google.com/presentation/d/1GuPC_pD84VFf4Yc8NKNDFBBmX6uY9DMA5CtKZoAdrzM/edit?usp=sharing) into the ECMAScript spect to add a new `formatToParts()` which would allow for this.
