### ISSUE TITLE
2.0 suggestion: Use context instead of injectIntl

### ISSUE THREAD

**Issue by MartijnHols** [yahoo/react-intl#357]
Hi, I've been playing around with the library for a while (thanks btw! it's awesome!) and my goal has been to try to get it to work without making the code much more complicated. I've gotten to a point where `injectIntl` is the only thing that is bothering me; by wrapping my components, it makes things harder such as using static methods (#196) and testing ([Testing with React Intl](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl)); most notably having to use .WrappedComponent (ugh), and conflicting with other libraries such as [rewire](https://github.com/jhnns/rewire).

Having also used [react-router](https://github.com/reactjs/react-router) I was wondering why this library doesn't use `context` in the same manner to transfer `intl` to deep components? This is a really easy to use interface intended for this kind of usage.

I changed the translations example to serve as an example: https://github.com/MartijnHols/react-intl/commit/b6566e270f1e3ff5909d4c5df2c97de3f645ff80. It works just as well and testing becomes much cleaner, users just have to provide a context object with intl assigned to get it to work (which actually makes sense);

(modified from the last example in [the Wiki](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl))
```
const intlProvider = new IntlProvider({locale: 'en'}, {});
const {intl} = intlProvider.getChildContext();
const context = {
    intl: intl
};
...
renderer.render(<RelativeDate date={date} />, context);
```

This completely eliminates the need for `injectIntl`.

**Comment by ericf** [comment]
The primary reason is this note from [React's `context` docs](http://facebook.github.io/react/docs/context.html):
> Context is an advanced and experimental feature. The API is likely to change in future releases.
Most applications will never need to use context. Especially if you are just getting started with React, you likely do not want to use context. Using context will make your code harder to understand because it makes the data flow less clear. It is similar to using global variables to pass state through your application.
>
> **If you have to use context, use it sparingly.**
>
> Regardless of whether you're building an application or a library, try to isolate your use of context to a small area and avoid using the context API directly when possible so that it's easier to upgrade when the API changes.

React has already changed `context` once in a major way, so `injectIntl()` provides an abstraction over `context`, similar to what you find in most Flux library's `connect()` function. This abstraction provides an indirection that allows React Intl to absorb any changes to `context` in the future.

If you want to use `context` directly in your app, feel free to do so, and you can use the [`intlShape`](https://github.com/yahoo/react-intl/wiki/API#intlshape) export on your component's `contextTypes`.

As I've mentioned in the the thread about statics, most people — I feel — are misusing statics in a way that becomes moot when the code base transitions over to using ES6 modules and heavy usage of function components.

**Comment by MartijnHols** [comment]
Sounds fair, thanks!

Since I'm already relying on `context` for react-router and not close to a release I'm not that hesitant to rely on `context` some more, especially given the advantages I mentioned. Besides, once we do get close to a stable release/have released, I don't think there will be much motivation to update the dependencies.

I must admit however that we're still new to the whole React/babel environment so we may still change this stance.

**Comment by ericf** [comment]
React Intl's out `<Formatted*>` components use `context` directly so if you're curious how they use it just check out their source.

**Comment by MartijnHols** [comment]
I had already rewritten my components using injectIntl to use the context approach. But the tests for these classes do show me I can [save 3 lines](https://github.com/yahoo/react-intl/blob/7f9003966e61e52daf5f5e6c0dfc8d0198db03ae/test/functional/format.js#L31) though. Awesome.

Thanks again.

**Comment by miracle2k** [comment]
FWIW, I came here to argue the same thing. For people who are interested, they might want to consider using a @injectIntl decorator, but one that simply declares the context:

    export function injectIntl(WrappedComponent) {
      WrappedComponent.contextTypes = WrappedComponent.contextTypes || {};
      WrappedComponent.contextTypes.intl = intlShape;
      return WrappedComponent;
    }

**Comment by ericf** [comment]
The Decorators proposals still has issues that need to be worked out before I'd feel comfortable providing one by default in the library, but you could of course make your own. Decorators are currently only specified for classes and class properties and not function declarations. With a push towards stateless function components in React, there would be a big void in the usefulness of an `@injectIntl` decorator.

Once the proposal moves forward and has resolved these issues, I think it'll end up being a great approach for this problem.

**Comment by taion** [comment]
Just found this issue thread. A few thoughts:

- The most likely changes to context going forward look to be restricting context to a single object, which is fully compatible with the current setup – we were comfortable enough doing this for React Router
- The current `injectIntl` function already works as a class decorator, though a proper decorator should probably declare `intl` as a property rather than just putting it in `props` (or `context`)
- It would be nice to document the `context` solution in the Wiki, if only as something semi-unstable for which particularly enterprising users can opt

**Comment by ericf** [comment]
@taion thanks for the feedback.

> The current injectIntl function already works as a class decorator, though a proper decorator should probably declare intl as a property rather than just putting it in props (or context)

Why do you think an instance prop would be more desirable than passing in the `intl` object as a prop?

**Comment by taion** [comment]
I tend to think that decorators shouldn't use HoCs, specifically for reasons of e.g. hiding statics, or muddying up semantics around refs, &c. – those are all vaguely anti-patterns but it's good to cause fewer surprises when possible.

That leaves setting up the relevant context type per something like https://github.com/yahoo/react-intl/issues/357#issuecomment-195744078, and it feels like you'd be hiding the React context stuff slightly better by making the decorator inject a `this.intl` rather than a `this.context.intl`.

It's really just – given a choice, if a decorator can avoid wrapping a component, then it'd be a win to not wrap that component, so you might as well set up an instance property to avoid having to go to `this.context` when avoidable.

**Comment by ericf** [comment]
@taion to be clear, `injectIntl()` isn't intended to be used as a decorator. It's a function that returns a new component which renders the passed-in component. It's only doing component composition and can work on any type of component including stateless function components.

Currently, class and class-property decorators are a Stage 1 ECMAScript proposal. One major gap in the current proposal is the missing semantics for how decorators work with function declarations. Given that React component authors are encouraged to write function components, decorators can't operate on them and there's no instance to hang an `intl` property on.

**Comment by taion** [comment]
Yup, I'm aware that `injectIntl` isn't really supposed to be used as a decorator – worth noting that its signature is the same as that of a decorator, though, and its semantics are roughly the same as e.g. the decorators in React DnD.

I came upon this thread mostly in the context of checking whether it was considered appropriate to use context (pun unintentional). Upon further thought, given how far away function decorators are, I'd think that using context might actually be the cleanest API for getting access to imperative hooks, moreso than adding an HoC.

**Comment by SachaG** [comment]
Just wanted to say that using context seems to work great so far, and is more intuitive to me than using HOCs.

**Comment by Robinfr** [comment]
I fully agree with just using the context. Testing is an absolute nightmare with the injectIntl.

**Comment by ericf** [comment]
@SachaG @Robinfr using `context` directly will likely be setting yourself up for major refactoring in the future when React changes how `context` works. React Intl's semver API contract is with `injectIntl()`. There are some docs on how to test components that use `injectIntl()`: https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#relativedate-advanced-uses-injectintl
