### ISSUE TITLE
FormattedTime prints date instead of time with timeZone

### ISSUE THREAD

**Issue by ludekstepan** [yahoo/react-intl#362]
Hi,
When using `<FormattedTime value={someValue} timeZone="UTC" />` the component prints a date instead of time. I think the problem is caused by line https://github.com/yahoo/react-intl/blob/master/src/format.js#L70 because it skips the defaults when the timeZone parameter is present.

**Comment by ericf** [comment]
Okay, I can look at restricting the props to just time-related things, and merging them with the defaults.

**Comment by ericf** [comment]
I dug in again, and this is a tricky issue because if I include `{hour: 'numeric', minute: 'numeric'}` by default, but you _only_ want hours, there's no way to unset the `minute` value.

I think the way forward is to remove `formatTime()` and `<FormattedTime>` since it's really no different than `formatDate()` and `<FormattedDate>`.

Another solution would be to use higher-level props which encapsulate the intend and can be mapped down to the `hour` and `minute` lower-level options.

**Comment by ludekstepan** [comment]
Hi Eric, thanks for looking into this. We have workarounded this by creating a custom stateless component that wraps the `<FormattedTime>` and provides all required props explicitly.

We plan to add higher-level definitions like 'TIME_SHORT', 'TIME_LONG' and similar to our components, so we are consistent across the whole application and we can easily find usages. We'll do something similar with the dates.

**Comment by ericf** [comment]
You can do this by providing named `formats` to the `<IntlProvider>` as well. But I think creating a higher-level component that wraps the corresponding `<Format*>` component, like you're doing, is a better solution.

**Comment by ericf** [comment]
I believe this was fixed by https://github.com/yahoo/react-intl/pull/597
