### ISSUE TITLE
All locales loaded?

### ISSUE THREAD

**Issue by julien-f** [yahoo/react-intl#364]
When I look at [the source](https://github.com/yahoo/react-intl/blob/master/src/index.js#L12), it seems that all locales are loaded by default.

But:

- it's in contradiction to what's explained in #162 (the user must load the wanted locale by themself)
- it looks like it's not working: unless I manually load a given locale, I get an error message (*Missing locale data for locale: "fr". Using default locale: "en" as fallback.*)

**Comment by ericf** [comment]
Sorry for the lack of docs on this — they still need to be written.

The `dist/` files only contain `en` locale data built-in by default, while the `lib/` files will load all locale data in Node, _but_ if they are packaged with Browserify, Webpack, or Rollup, they will only include the `en` locale data like the `dist/` files. This is done via the `"browser"` entry in `package.json` which JS bundlers will read and respect.

The reason for this is that shipping all the locale data to the browser would be very wasteful because you only need the data for one language at a time. While on the server, all locale data will be loaded.

If you're app only supports a small number of locales, it's probably simpler to package all the locale data up in your JS bundle, especially if you're supporting changing the locale dynamically (#365). You can do that my simply importing the locale data modules in your bundle's entry point: https://github.com/yahoo/react-intl/wiki/API#addlocaledata

If you need to support many languages, then you'll probably want to take a different approach to loading the locale dynamically via separate `<script>`s.

**Comment by julien-f** [comment]
Ok, thanks for the clarification :)
