### ISSUE TITLE
Loading translation strings/dicts conditionally.

### ISSUE THREAD

**Issue by pypetey** [yahoo/react-intl#367]
I have 2 language files:

import {defineMessages} from 'react-intl';

de.js
```
const messages = defineMessages({
    label_password: {
        id: 'password',
        description: 'Label for passwords',
        defaultMessage: 'Passwert'
    }
})

export default messages
```

en.js
```
import {defineMessages} from 'react-intl';

const messages = defineMessages({
    label_password: {
        id: 'password',
        description: 'Label for passwords',
        defaultMessage: 'Password'
    }
})


export default messages
```

I initialize that in my main component:

```
import React, { PropTypes } from 'react'
import { Provider } from 'react-redux'
import { Router } from 'react-router'
import {IntlProvider} from 'react-intl'
import en from './locale/en'
import de from './locale/de'

export default class Root extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            translations: {}
        }
    }

    componentWillMount() {
        let translation = this.get_locale()
        var locale = en
        if (translation === 'en') {
            locale = en
        } else if (translation === 'de') {
            locale = de
        } else {
            locale = en
        }
        this.setState({
            translations: locale
        })
    }

    get_language(locale) {
        const dash_index = locale.indexOf('-')
        if (dash_index >= 0) {
            return locale.substring(0, dash_index)
        }
        return locale
    }

    get_locale() {
        var detected_locale = navigator.language || navigator.browserLanguage
        var language = this.get_language(detected_locale);

        if (['en', 'de'].indexOf(language) !== -1) {
            return language
        } else {
            return 'en'
        }
    }

    static propTypes = {
        history: PropTypes.object.isRequired,
        routes: PropTypes.element.isRequired,
        store: PropTypes.object.isRequired
    }

    get content() {
        return (
            <Router history={this.props.history}>
                {this.props.routes}
            </Router>
        )
    }

    get devTools() {
        if (__DEBUG__) {
            if (__DEBUG_NEW_WINDOW__) {
                if (!window.devToolsExtension) {
                    require('../redux/utils/createDevToolsWindow').default(this.props.store)
                } else {
                    window.devToolsExtension.open()
                }
            } else if (!window.devToolsExtension) {
                const DevTools = require('containers/DevTools').default
                return <DevTools />
            }
        }
    }

    render() {
        return (
            <IntlProvider locale={this.get_locale()} defaultLocale='en' messages={this.state.translations}>
                <Provider store={this.props.store}>
                    <div style={{ height: '100%' }}>
                        {this.content}
                        {this.devTools}
                    </div>
                </Provider>
            </IntlProvider>
        )
    }
}

```

I get a warning in command line:
`[React Intl] Missing message: "password" for locale: "de", using default message as fallback.`

I understand that this problem appears because I'm loading language files conditionally and it looks for 'de' language file even tough it's loaded.

Is there a way to load my translation files in a way such warning will not appear?

**Comment by ericf** [comment]
Using `defineMessages` only makes sense if you're also using the [Babel plugin](https://github.com/yahoo/babel-plugin-react-intl) to extract them. You should also use this to define your app's **default** messages in the **default** locale, not for every locale.

- Some details about [`defineMessages`](https://github.com/yahoo/react-intl/wiki/API#definemessages) on the Wiki.
- Look at the [Translations Example App](https://github.com/yahoo/react-intl/tree/master/examples/translations)
- `<IntlProvider>` expects to receive a `messages` prop that's a flat `{"messageId": "translated string"}` object at runtime, even for the default messages.

**Comment by timkraut** [comment]
@ericf I have got a similar issue: I use JSON files for every component which contains the translations. They are combined with a Gulp task into a single JSON file for every language. The default language is determined dynamically (depending on the browser) and can be set manually afterwards. If the browser language is not `'en'`, I receive messages like `Missing message: "<translationKey>" for locale: "<language>", using default message as fallback.`.
As I've defined `defaultMessage` properties for all components, I would expect them to be used until the correct locale file is loaded. And that's what happens BUT for every translation key, an error message is displayed in the console. This makes debugging pretty difficult as I have to scroll constantly to see the actual debugging/error messages that I'm looking for. Is there any way to disable these messages? I don't want to define all translation keys again in order to pass them into `<IntlProvider messages={...}>...</IntlProvider>` as this would sacrifice the reuse of any component.

**Comment by ericf** [comment]
@timkraut the docs should probably be more explicit on this point: the `defaultLocale` prop on `<IntlProvider>` should match the language of the `defaultMessage` prop on any `<FormattedMessage>` or `defineMessages()`; i.e., it's the **app's** default language and what its source strings are written in.

**Comment by timkraut** [comment]
@ericf I have not defined `defaultLocale` on `<IntlProvider>`. Setting this property explicitly to `"en"` or `"de"` doesn't change anything.
I use `IntlProvider` as follows: `<IntlProvider locale={this.props.currentLanguage} messages={this.props.translations}>...</IntlProvider>`. I use Redux to update the property `currentLanguage`. If `currentLanguage` is set to `"en"`, everything works fine. If I change the language to `"de"`, they aren't available immediately (they are downloaded asynchronously) so I see lots of error messages in the console.

**Comment by ericf** [comment]
> the translations aren't immediately available (they are downloaded asynchronously) so I see lots of error messages in the console.

Okay, so you have to write you code to wait for the translations to be loaded before you update the props on `<IntlProvider>`.

**Comment by timkraut** [comment]
@ericf The issue arises during the app initialization if the browser language is not `"en"`. At the moment, I have defined `translations = {}` and would expect React-Intl to use the `defaultMessage` keys *silently*. Setting `translations` to `null` doesn't work either. Is there any other possibility to avoid having dozens of error messages in the console?

**Comment by ericf** [comment]
> As I've defined defaultMessage properties for all components, I would expect them to be used until the correct locale file is loaded.

This is not how React Intl works, it's just like any other React component and it'll use the props you provide.

> Is there any other possibility to avoid having dozens of error messages in the console?

The console messages are only shown in development and are there to help guide you through fixing issues. Normally how people would handle this issue is have the server embed the translations for the users locale based on the `Accept-Language` HTTP header. The other approach you'll need to do is simply wait to render the app until the translations have been downloaded from your server.

If these error messages weren't there, people would be confused as to why messages they know they have translations for are showing up in their app's default language.

**Comment by timkraut** [comment]
@ericf 
Just to be sure that I understand this correctly, either I have to adapt my development environment to this library, copy all translation keys into the initial props object, accept a negative performance impact/perception because I have to wait for the download of all translation keys or accept the console messages?

What do you mean by "The console messages are only shown in development"? What do I have to do to enable the production/non-development mode? I'm not using Webpack-Dev-Server if that's a requirement.

I totally understand what these error messages are there and they are actually quite useful to find missing keys. I'm just not sure whether I like them to be always there. Using an (opt-in like in angular-translate)[https://angular-translate.github.io/docs/#/guide/16_error-handling] would help me a lot.

**Comment by ericf** [comment]
If `locale` and `defaultLocale` on `<IntlProvider>` are the same — which is the general case when developing — then there won't be errors. `defaultLocale` is the locale that the app's `defaultMessage`s are defined in. I think it's reasonable to assume that in development, `locale` === `defaultLocale`. I'd encourage you look over the code [here](https://github.com/yahoo/react-intl/blob/cc50a9806859cfddab5ff24bb9df46c6e72cd88b/src/format.js#L220-L232).

If you want to test your app with a `locale` other than the `defaultLocale`, then yes, you must provide the translations and you'll have to wait for them to load over the network, otherwise you'll see the errors.

The `.min.js` file doesn't contain any `console.error` messages.

**Comment by timkraut** [comment]
@ericf I don't think that `locale` and `defaultLocale` are generally the same. Currently, I work in Luxembourg. I am German so my browser is in German. The colleague sitting next to me is French so his browser is in French and there are colleagues which use English browsers, too. Collaborating on the same piece of software with several browser languages is no exception but rather the standard case in Luxembourg. 

Thanks for the link. Setting my `NODE_ENV` to `production` might be the easiest solution at the moment - even though it's a little bit hacky.

**Comment by ericf** [comment]
@timkraut you should just bite the bullet and do the right thing of loading messages in dev. That's what we do, since you have to do it in prod anyways.

**Comment by timkraut** [comment]
@ericf I don't think that I share your idea of "the right thing". Currently, I use BrowserSync during development. This happens completely static. Bundling the correct locale files with the rest of the application would mean to build a dynamic server manually and changing the entire build pipeline just for React-intl. Maybe your setup at Yahoo supports this but I would appreciate if you could consider that not everyone has your environment. 
I agree that another solution might be necessary for production. But that's an entirely different environment. Locally, I use a Node.js server via BrowserSync whereas the production server runs with Java. This means of course that the production build pipeline can't be the same.

**Comment by ericf** [comment]
@timkraut I spent time helping you even though I considered your comments to be hostile. No one is forcing you to use this library, it's open source, do with it what you please. I'm locking this issue because I don't want to continue this discussion while you have a negative, condescending attitude towards my comments.
