### ISSUE TITLE
Translate the Prop of a Component?

### ISSUE THREAD

**Issue by joncursi** [yahoo/react-intl#438]
How does one use this library to translate the _prop_ of a component (not using `<FormattedMessage />`? As an example:

`en-US.json`:

```json
{
  "app.title": "Example English Title Here."
}
```

Component:

```jsx
import React, { Component } from 'react';
import AppBar from 'material-ui/AppBar';

...

<AppBar
  title="Translate me!"
/>
```

AppBar is imported from a library, so you don't have the ability to specify the translation directly within that component itself. It has to be done on the prop line above. Thanks!

**Comment by langpavel** [comment]
You have a choices.
First:
```jsx
<FormattedMessage ...>
  {text => <AppBar title={text} />}
</FormattedMessage>
```
Second is use [injectIntl](https://github.com/yahoo/react-intl/wiki/API#injection-api) as documented, then just call `this.props.intl.formatMessage(messageDescriptor: MessageDescriptor, values?: object) => string`

**Comment by ericf** [comment]
@joncursi If `title` is rendered as a child of another component, then you could set its prop type to `PropTypes.node` and then use `title={<FormattedMessage .../>}`.

@langpavel that won't work in all cases since the function passed as a child to `<FormattedMessage>` will receive an array of `PropType.node`s, not a string.

**Comment by langpavel** [comment]
Eric, thanks for explanation ;-)

**Comment by joncursi** [comment]
Thank you @ericf !
