### ISSUE TITLE
Move console.errors about `addLocaleData` to where the data is required

### ISSUE THREAD

**Issue by limscoder** [yahoo/react-intl#453]
[These docs](https://github.com/yahoo/react-intl/wiki#loading-locale-data) describe that loading locale data is required for programmatic pluralization and relative formatting. 

I'm not using either of those features. I don't think I need that data for anything, and I'd rather not load it if I don't have to, but react-intl console.errors a message about not having it. Would you accept a PR to move the check into the components where that data is needed?

**Comment by ericf** [comment]
How would you output numbers in a UI when most require labels, which then leads to needing pluralization?

**Comment by limscoder** [comment]
Doesn't all number formatting go through `Intl.NumberFormat`?

**Comment by ericf** [comment]
Yes all number formatting goes through `Intl.NumberFormat`, but plural formatting goes through `intl-messageformat` which needs the locale data for plural rules. This means that you do in fact need to be loading the locale data for your app.

Since it's likely that any app that needs to display a number will also need to label that number, most apps will end up needing to use pluralization like you are, and therefore need the locale data to support it.

**Comment by limscoder** [comment]
So, the `field` data is required for `<FormattedRelative />` and I assume the pluralization function is required for `<FormattedPlural />`, is that correct?  `<FormattedMessage />` appears to correctly format ICU plurals like `"{count, plural, =1 {Child} other {Children}}"` without this data.

We're not using either `<FormattedRelative />` or `<FormattedPlural />` at this time, so if you're not open to a pull request to move the checks into those components, then I'll mock the data out to avoid the warning, which appears to work ok:

```
addLocaleData({
  fields: {},
  locale: locale,
  pluralRuleFunction() {}
});
```

**Comment by ericf** [comment]
`<FormattedMessage>` uses `pluralRuleFunction`. "en" locale data is built in, change the locale to "fr" or something else and you'll see it failing to work correctly.
