### ISSUE TITLE
FormattedPlural: attributes such as 'zero' or 'two' do not work

### ISSUE THREAD

**Issue by kongakong** [yahoo/react-intl#473]
It seems like `FormattedPlural` ignore attributes `zero` or `two` in my example below. `one` and `other` work as expected.

      <FormattedPlural
        value={found}
        zero={"Nothing"}
        one={"Got one"}
        two={"Got two"}
        other={`Got ${found}`}
      />

**Comment by ericf** [comment]
Yeah, that's because they are locale specific: http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html

If you have time, you could edit the docs to be more clear about this for the next person who runs into this: https://github.com/yahoo/react-intl/wiki/Components#formattedplural
