### ISSUE TITLE
Purpose of `injectIntl`

### ISSUE THREAD

**Issue by singles** [yahoo/react-intl#474]
I would like to start from apologizing for posting question in issues, I tried to found some IRC/gitter to ask that question, but I couldn't. 

Thing is.. What's the purpose of `injectIntl`? 

Docs are saying that if you want to use `formatMessage` and rest directly, you have to use `injectIntl` to wrap component with HOC. So like below:

```js
import React, {PropTypes} from 'react';
import {injectIntl, intlShape, FormattedRelative} from 'react-intl';

const Component = ({date, intl}) => (
    <span title={intl.formatDate(date)}>
        <FormattedRelative value={date}/>
    </span>
);

Component.propTypes = {
    date: PropTypes.any.isRequired,
    intl: intlShape.isRequired,
};

export default injectIntl(Component);
```

But why not use `this.context.intl...` ?

```js
import React, {PropTypes} from 'react';
import {intlShape, FormattedRelative} from 'react-intl';

const Component = ({date}, context) => (
    <span title={context.intl.formatDate(date)}> //change here, use context directly
        <FormattedRelative value={date}/>
    </span>
);

Component.propTypes = {
    date: PropTypes.any.isRequired,
};

Component.contextTypes = {
    intl: intlShape.isRequired,
}

export default Component;
```

From what I saw HOC component provided by `injectIntl` it's using `contextTypes` internally. 

I believe I'm missing something - I just don't know what...

**Comment by ericf** [comment]
This has been answered in various other places. In short, `injectIntl` provides a layer of indirection that decouples using React Intl from using React's `context` feature directly. This way if/when React changes how context works, the code change can be centralized in `injectIntl` instead of many components within all the apps that use React Intl.

Also:
> Context is an advanced and experimental feature. The API is likely to change in future releases.
Most applications will never need to use context. Especially if you are just getting started with React, you likely do not want to use context. Using context will make your code harder to understand because it makes the data flow less clear. It is similar to using global variables to pass state through your application.
>
> If you have to use context, use it sparingly.
>
> Regardless of whether you're building an application or a library, try to isolate your use of context to a small area and avoid using the context API directly when possible so that it's easier to upgrade when the API changes.

http://facebook.github.io/react/docs/context.html

**Comment by danday74** [comment]
the question (not the answer) answered my question

**Comment by DavideDaniel** [comment]
I do want to point out that despite that warning, context is the only thing that has NOT changed at all...
