### ISSUE TITLE
Cannot use `injectIntl` as a decorator with options

### ISSUE THREAD

**Issue by julien-f** [yahoo/react-intl#498]
It would be nice if `injectIntl` could be used as a decorator when using options:

```js
@injectIntl({ withRef: true })
export default class FooBar extends Component {/* ... */}
```

**Comment by ericf** [comment]
It's unclear what the semantics of decorators are. Class and Property Decorators are still an ECMAScript Stage 1 (of 4) proposal: https://github.com/tc39/proposals

In the case of `injectIntl` it's not mutating a component class (which is what a decorator would do), instead it's a function that produces a new component class which will **render** the specified component passed in. That component could be an ES6 class, `React.createClass` or stateless function component.

**Comment by julien-f** [comment]
[react-redux's `connect()`](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) is a decorator, even if it just wraps the component.

And I believe that wrapping in a higher order component is a valid React pattern for decoration. It will probably even become a [first class citizen](https://github.com/facebook/react/issues/6974).

**Comment by ericf** [comment]
> Decorators make it possible to annotate and modify classes and properties at design time.

It's not a decorator, it doesn't modify the class.

**Comment by julien-f** [comment]
Decorator is a term which may holds many semantics, and the current proposal allows more than just modifying the class, otherwise why would it use the return value of the class?

Anyway, I can understand that you don't want to change `injectIntl` but you are simply dismissing the idea without any regards to my argumentation and existing implementations.
Don't you value redux-react experience?

**Comment by ericf** [comment]
How would it work with a stateless function component?

**Comment by julien-f** [comment]
First I just want to suggest that I do not want to change the behavior of `injectIntl`, I am just saying that it would be nice if it could also behave as a decorator.

Regarding your question, react-redux's `connect` can perfectly be used with with stateless components (as you can see in the [many examples](https://github.com/reactjs/react-redux/blob/master/docs/api.md#examples)).

**Comment by ericf** [comment]
My point is that decorators don't work on function declarations. This means there'd be two syntaxes for using `injectIntl`, one for people who want to use decorators to wrap components defined as ES6 classes, and another wrap stateless function components.

I searched the React Redux docs and found no examples or docs of using decorators. The reason decorators are supported for `connect()` is that it takes a currying approach, where calling `connect()` gives you a customized HOC factory function for which you call and pass in a component to wrap.

This API makes sense for `connect()` because you're usually providing a `mapStateToProps` implementation. While in the case of React Intl, there isn't this need for customization.

**Using current `injectIntl()` API:**
```js
export default injectIntl(({intl ...props}) => (
    <span title={intl.formatDate(props.date)}>
        <FormattedRelative value={props.date} />
    </span>
));
```

**Using `connect()`-style API:**
```js
export default injectIntl()(({intl ...props}) => (
    <span title={intl.formatDate(props.date)}>
        <FormattedRelative value={props.date} />
    </span>
));
```

I think people will find it odd that they will be using `injectIntl()(MyComponent)` and likely never passing any arguments to the first function.

It's possible to overload `injectIntl()` to accept `options` and return a function, or a component and return another component, but this gets back to my original rejection of this idea, which is, there is now two ways of doing something and it's a refactor hazard as you move components to stateless function components. I don't see the value provided by the Stage 1 decorator syntax — which hasn't progressed much in two years — for this use case.

**Comment by chapati23** [comment]
@julien-f i was surprised by this as well. we're using [recompose](https://github.com/acdlite/recompose) to compose multiple decorators (CSSModules, Redux, react-intl)

you can use lodash's [curryRight](https://lodash.com/docs#curryRight) to enable using `injectIntl` as a decorator:

```javascript
const injectIntlDecorator = curryRight(injectIntl)
export default compose(
  injectIntlDecorator(),
  connect(mapStateToProps, mapDispatchToProps)
)(MyComponent)
```

**Comment by VyvIT** [comment]
Are there any suggestions, how to use this with { withRef: true } option?
I'm getting "Cannot call a class as a function" exception.
```
const injectIntlDecorator = curryRight(injectIntl)
export default compose(
 injectIntlDecorator({ withRef: true }), //<------------ DOESN'T WORK
  connect(mapStateToProps, mapDispatchToProps),
  CSSModules(styles)
)(MyComponent)
```

**Comment by damiangreen** [comment]
To answer my own question,

 whilst `curry` worked fine in jsx, when migrating my component to Typescript I had to use `curryRight` ([from ramda-adjunct](https://char0n.github.io/ramda-adjunct/1.16.0/RA.html#.curryRight))
