### ISSUE TITLE
Breaking change introduced in v2.1.3!

### ISSUE THREAD

**Issue by clayreimann** [yahoo/react-intl#503]
In version 2.1.2 you could do this:

```javascript
import ReactIntl from 'react-intl'
ReactIntl.addLocaleData(/* stuff */);
```

In 2.1.3 that same code throws an exception, instead you must do:

```javascript
import {addLocaleData} from 'react-intl';
addLocaleData(/* stuff */);
```

If this was unintentional please revert the change and mark 2.1.3 as invalid, otherwise publish 2.1.3 as 3.0.0 and mark 2.1.3 as invalid.

**Comment by ericf** [comment]
There was a change in Rollup (which is used to build this library) to add the `__esModule` flag to the CommonJS output. This flag then allows Babel to **correctly** compile _your_ code using ES Module semantics (which you're opting-in to by using `import` syntax).

**This is not a valid `import` statement for React Intl** because it does not have a default export, instead everything is a named export.
```js
import ReactIntl from 'react-intl'
```

If you like using the namespacing pattern in your code and having a `ReactIntl` namespace, you need to fix your code to be correct in one of the following ways:

```js
// Use CommonJS which will have the correct semantics and give you a namespace.
const ReactIntl = require('react-intl');

// Use `import` with correct semantics to get a namespace.
import * as ReactIntl from 'react-intl';

// Use named exports since React Intl has no default export.
import {addLocaleData} from 'react-intl';
```

I don't consider this a breaking change because there was never any intention of supporting the `import` syntax you had in your app since React Intl doesn't offer a default export, only named exports. So I have no plans to release a new version, or mark 2.1.3 as invalid. This should be a simple change on your end to correct your `import` statement, it was a bug that it ever worked before.
