### ISSUE TITLE
HTML tags in messages

### ISSUE THREAD

**Issue by arwinder3** [yahoo/react-intl#504]
Hi,

I have wrapped my root App component in an IntlProvider and I use `<FormattedMessage> `and it works fine. However, I also have nested Modal components within the App, which are rendered outside of the root application as a direct child of the body.

This means that I can't use `<FormattedMessage>` in the modal components, I think it's because the IntlProvider is no longer an ancestor of the modal since it is added as a child of the body.

So to overcome this issue I used injectIntl and then use intl.formatMessage(). However, some of the messages need some HTML tags, for example <strong></strong>... and I can't see a way to do this using intl.formatMessage().

So far I've tried:
within the render method of the modal...

              <ModalSection>
                  {intl.formatMessage({id: "app.greeting"},
                      {
                          name: <strong>name</strong>
                      }
                  )}
              </ModalSection>

This prints out [Object object]

Any help is greatly appreciated!

Cheers,
Arvy

**Comment by ericf** [comment]
`formatMessage` will always return a string, whereas `<FormattedMessage>` will return a React element, this is how the component can support nested elements passed as placeholder values for the message.

With modals that are rendered outside of the React tree's DOM root, I'd recommend using ` ReactDOM.unstable_renderSubtreeIntoContainer` because it'll preserve the component hierarchy context, but allow for the DOM nodes to have a different root. See: https://github.com/facebook/react/issues/4819#issuecomment-138951906

This is how the `react-modal` package handles creating a modal that disconnect at the DOM tree level, but still within the React component hierarchy: https://github.com/reactjs/react-modal/blob/master/lib/components/Modal.js#L78

**Comment by arwinder3** [comment]
Awesome, thanks a lot for the prompt response. Will take a look =)
