### ISSUE TITLE
Change format style for <FormattedRelative />

### ISSUE THREAD

**Issue by geekyme** [yahoo/react-intl#515]
Instead of rendering `27 minutes ago`, how can I configure `<FormattedRelative />` to render 27m ago?

**Comment by ericf** [comment]
This isn't supported by the `intl-relativeformat`, it's unclear if this exact form would ever be supported since `m` can be ambiguous between "minutes" and "months". All locale data is sourced from Unicode CLDR, and we're working on standardizing relative time formatting in JS: https://github.com/caridy/intl-relative-time-spec

It would be best to open this issue in that repo.
