### ISSUE TITLE
Problem with defaultLocale and FormattedMessage value format

### ISSUE THREAD

**Issue by SimeonC** [yahoo/react-intl#527]
I have a problem with defaultLocale and message formatting. The problem piece of code is here:
```
<FormattedMessage
	id="components.bookingSidebar.surchargeAmount"
	defaultMessage="Credit Card Surcharge ({surcharge, number, percentage} of payment)"
	values={{
		surcharge: summary.surchargePercentage
	}}
/>
```

If I setup my IntlProvider as `<IntlProvider ... defaultLocale="en-NZ" messages={undefined}>...` then this outputs `Credit Card Surcharge (0.0046 of payment)`.

If I setup my IntlProvider as `<IntlProvider ... messages={require('../en-NZ.json')}>...` then this outputs `Credit Card Surcharge (4.6% of payment)`.

My formats is setup like this:
```
number: {
	'percentage': {
		style: 'percent',
		maximumFractionDigits: 2
	}
},
```
Interestingly enough this only occurs using FormattedMessage, FormattedNumber or this.props.intl.formatNumber display the value correctly both ways.

**Comment by ericf** [comment]
If a message was missing, then it'll fallback to format the `defaultMessage` using the `defaultLocale` and `defaultFormats` provided to `<IntlProvider>`. You can see the code [here](https://github.com/yahoo/react-intl/blob/f3398e265971748d461a4aa669924ff6ed2603f1/src/format.js#L239-L254).

What you'd want to do is supply a value for the `defaultFormats` props to `<IntlProvider>`: https://github.com/yahoo/react-intl/wiki/Components#intlprovider

**Comment by SimeonC** [comment]
Ah, thanks for clearing that up. I wasn't expecting the fallbacks to be linked like that, I thought it'd always use the `format` if provided even if we fall back to defaultMessage.

**Comment by ericf** [comment]
Yeah it should be documented better. There might be cases where different named formats are used between the default message and the translations which is why during the fallback process they are linked together.

If you think of a good way to improve these docs, feel free to update them 😄
 
- https://github.com/yahoo/react-intl/wiki/Components#message-formatting-fallbacks
- https://github.com/yahoo/react-intl/wiki/API#message-formatting-fallbacks
