### ISSUE TITLE
Display "a few seconds ago" instead of the amount of seconds if < 1 minute

### ISSUE THREAD

**Issue by Noxalus** [yahoo/react-intl#530]
Hello everyone.

I'm using this package to display the time of each messages in a chat application like this:

```
<FormattedRelative value={date} />
```
It works pretty well, but I don't want to display the amount of seconds since the message has been post if this time doesn't exceed at least 1 minute. In this case, I would like to display *A few seconds ago* instead.

I've browsed the documentation, and I thought that specify the unit will be enough, but it's not:

```
<FormattedRelative value={date} units='minute' />
```
With this code, it displays "In 0 minute" :open_mouth: 

Do you know how if I can do that directly using this *FormattedRelative* component?

Thank you in advance for your help. :smile: 

PS: I'm using a previous version of this package => **1.2.0**

**Comment by ericf** [comment]
We don't currently have data for all 200 languages for "a few seconds ago". This data might exist, but it's not currently supported.

I would recommend wrapping `<FormattedRelative>` with a component that implements the custom business logic you're looking for and you could provide your own translations for "a few seconds ago":

```js
import {
    injectIntl,
    FormattedMessage, 
    FormattedRelative
} from 'react-intl';

export default injectIntl(({intl, ...props}) => (
    <FormattedRelative {...props}>
        {(formattedRelative) => {
            if (intl.now() - props.value < 60000) {
                return (
                    <FormattedMessage
                        id='seconds_ago'
                        defaultMessage='a few seconds ago'
                    />
                );
            }

            return formattedRelative;
        }}
    </FormattedRelative>
));
```

**Note:** This is using the 2.0 API, here's how to upgrade: https://github.com/yahoo/react-intl/wiki/Upgrade-Guide

This is kind of a gross way to do this using the function-as-child pattern, and effectively accessing `Date.now()` inside of a render function, but since this logic is already wrapped by `<FormattedRelative>`'s render method, it's not as bad, since this nested function will only be called when the outer `<FormattedRelative>` component renders.

**Comment by Noxalus** [comment]
Thank you so much @ericf, I will try this :+1:
