### ISSUE TITLE
Format currency within a FormattedMessage

### ISSUE THREAD

**Issue by amannn** [yahoo/react-intl#539]
Is this possible?

With a string like "This product costs {price, number, currency}." I get the error message `TypeError: Currency code is required with currency style.`. How is it possible to specify the `format`? I couldn't find such a `prop` for `FormattedMessage`.

**Comment by ericf** [comment]
You can specify custom, named formats via the `formats` prop on `<IntlProvider>`. There's also `defaultFormats` which are used with the `defaultLocale` in the fallback case because the `formats` might be dependent on the `locale`. Here's an example with `<FormattedMessage>` and `<FormattedNumber>` using a custom named number format `USD`:

```js
const formats = {
    number: {
        USD: {
            style: 'currency',
            currency: 'USD'
        }
    }
};

<IntlProvider
    locale='en'
    messages={{
        price: 'This product costs {price, number, USD}'
    }}
    formats={formats}
    defaultFormats={formats}
>
    <FormattedMessage id='price' values={{price: 1000}}/>
    <FormattedNumber value={1000} format='USD'/>
</IntlProvider>
```

Sorry there isn't detailed docs for this feature yet… I need to add them!
