### ISSUE TITLE
Negative currency values using FormattedNumber are displayed inside brackets in IE.

### ISSUE THREAD

**Issue by ladvishal1985** [yahoo/react-intl#568]
Hi,
We are using FormattedNumber for displaying currencies. The values can be in negative. Hence if our currency value is  -**183792.25** then in Chrome it is displayed as **-€183,792.25** and in IE11 it is displayed as **(€183,792.25)**. Not sure of this different behavior. But if somehow we can have some setting to chose the format that can be consistent across browsers.

**Comment by ericf** [comment]
This is unfortunate. You might want to open an issue against IE. To get around this issue, you could load the [Intl.js](https://github.com/andyearnshaw/Intl.js) polyfill in IE11.

**Comment by thedamon** [comment]
parentheses to indicate negative numbers is a legitimate way to do it. You'll see it a lot in accounting software. So it's not really a browser bug so much as it is a failure of the spec to properly specify.

**Comment by vijyethad** [comment]
We are using FormattedNumber for displaying currencies. For negative values we would like to show within parenthesis. 
Example:-$5 will be ($5). 
I don't see a way to achieve this with FormattedNumber. My only option is to move away from using FormattedNumber?

**Comment by papasmile** [comment]
While React Intl does have a lot of features, it's actually an Internationalization/Localization framework[1] and so is FormatJS[2].  Can anyone point to a legitimate locale/region that formally declares parenthesis for negative numbers?  If so, it might belong somewhere in a higher-order spec; if not, it has got nothing to do with internationalization.

[1] https://github.com/yahoo/react-intl#react-intl
[2] https://formatjs.io/guides/basic-i18n/#what-and-why

**Comment by thedamon** [comment]
@vijyethad just use IE11 and it will be in parentheses 😉 

(i know, not helpful.. but.. this is how it appears to work as browsers have implemented the Intl library in differing ways.. reminds me of how the HTML5 form validation seemed so nice until every browser implemented it differently)

**Comment by thedamon** [comment]
@papasmile there are a lot of locales and regions that do not have formal declarations of how to format things, and even if they did, what if no one typically follows the government recommendations? (we generally build things for humans not bureaucrats ;)) which is why I think a localization framework is not entirely successful when it doesn't provide any options to specify common methods of formatting strings.

Concerning negative numbers, the bureaucrats (accountants) generally use parentheses to denote a negative number. So as long as they stick to IE11 they will be happy. As far as requests from business in my line of work, this might work fairly decently since it's usually they that use IE 😄

**Comment by papasmile** [comment]
@thedamon totally with you there; I would say 'common use' counts as a 'formal declaration' in many cases.  Just suggesting that as "bureaucrats (accountants)" is not a locale or region so it's not related to localization.
