### ISSUE TITLE
Safari 9.1 does not use options on FormattedDate

### ISSUE THREAD

**Issue by IsurusPrime** [yahoo/react-intl#580]
tried setting the month/day/year options on the Formatted Date, and all it output as a string M/D/YYYY.

Chrome works fine and returns the options as expected.  2-digit worked on day, month and year just fine.

**Comment by ericf** [comment]
Safari 9 doesn't contain the `Intl` built-in APIs. You need to use a polyfill: http://formatjs.io/guides/runtime-environments/#client

**Comment by jochienabuurs** [comment]
Even though i'm loading the polyfill, i still don't have the correct date format displayed. Using the following config:
`
<FormattedDate
  value={date}
  year='numeric'
  month='long'
  day='2-digit'
  weekday='long'
/>
`
i get the correct output in chrome, firefox and safari 10, but not in safari 9.
In safari 9 it still states "Vr 21 Okt. 2016" (no long names, but short).
This tells me that the Intl API polyfill is correctly loaded (otherwise i would get an error).
So why is it giving me a short name instead of a long one?

**Comment by ericf** [comment]
@jochienabuurs The Intl Polyfill only contains a subset of the total locale data, therefore some combinations aren't currently supported. There's some open issues on the Intl repo about this. It comes down to a balance between compatibility and file size.
