### ISSUE TITLE
Jest snapshot testing for application with React Intl (example + docs)

### ISSUE THREAD

**Issue by zouxuoz** [yahoo/react-intl#681]
Hi, I've created [example](https://github.com/zouxuoz/react-intl-jest-example) and want to write some docs about Jest snapshot testing with React Intl for your [wiki page](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#jest). How I can contribute this to your repository?

**Comment by ericf** [comment]
@zouxuoz awesome! 🎉 Anyone can edit the Wiki, so feel free to do so. For the example app, we've started switching to use `create-react-app` for the apps in the `./examples/` dir. Since it supports Jest testing out of the box, it would be best to use it to create the Jest example app, which you can then sent a PR for.

* https://github.com/facebookincubator/create-react-app
* https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#running-tests
* https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#experimental-snapshot-testing
