### ISSUE TITLE
Can locales files be splitting?

### ISSUE THREAD

**Issue by ImJoeHs** [yahoo/react-intl#720]
Hello, i am adding react-intl to a big application , the translation file would be huge and also it is redundant to load this file at one time. So how can I do the code spliting with the locales files?

**Comment by ericf** [comment]
Yes it's possible to do this. You'll end up with code having an implicit dependency on it's translated strings which you'll have to manage based on how your splitting the code.

I think the best way to handle this is using nested `<IntlProvider>` instances. Say you have an app using React Router and code split on routes. You can have a top-level `<IntlProvider>` with the app-shell string `messages` passed-in, along with nested `<IntlProvider>`s around each route component with the route-specific `messages` passed-in.

See: https://github.com/yahoo/react-intl/tree/master/examples/nested

**Comment by ImJoeHs** [comment]
Thanks a lot!

**Comment by slorber** [comment]
@ericf this goes against opinion of @caridy [here](https://github.com/yahoo/react-intl/issues/76) but why not provide translations on a per-component basis? it does not mean that some translations can't be common/shared across components.

Also wonder but if we code-split on a page basis, then when we load the page bundle, it will likely load all the translations for this page.

Is there any way so that we only load the translations for the current language and for the currently displayed components?


I see multiple approaches here:
- One big fat translation bundle / app bundle
- One translation bundle per lang in addition to your regular app bundles
- One translation bundle per page (or split point), containing multiple translations
- One bundle per page, containing only the current lang

I don't really need something very advanced as I currently only have 2 languages but just wondering what's the best way to code-split bundles. Even with 2 languages translations start to represent quite a big size for my app.


What I understand is that we have to avoid splitting in too much small bundles because it would create too much additional http requests, but then what's the best strategy?


What I'm thinking could be a good solution:
- Each page expose a component entry-point, and an entry-point per lang
- When user displays a page, we load page component + current lang entry point and then render
- Language entry points could be created thanks to some kind of dependency system between component translations
- We should be able to have common translations being put in a common webpack chunk


I'm not sure how the component translation dependencies can be expressed, maybe it can be quite similar to what Relay/GraphQL does.

**Comment by ericf** [comment]
We do something like this at Yahoo. We have the UI broken down into "applets", which provide a feature/function. We reuse these applets across our sites and they are self contained with their own strings. An app is basically a collection of applets and they will be loaded async via Webpack. When an applet is rendered inside a main app, it's wrapped in an `<IntlProivder>` and provided its strings.

I think what you're getting at is ideal and possible, but only required after an app becomes very large.

**Comment by slorber** [comment]
Thanks for the feedback. An "applet" or a page is quite similar imho.

So at yahoo when an Applet loads it loads all the applet locales at once, even the unused ones?


I'm just wondering things without real production usecase, particularly how this could be setup by default in opinionated tools like NextJS which already does code-splitting by default

**Comment by ericf** [comment]
It's different. A page has many applets.

**Comment by ericf** [comment]
Speaking of Next.js, I actually plan to work on a React Intl example app for it 😀

**Comment by slorber** [comment]
@ericf have you worked on the React Intl example yet? I'd be happy to take a look so please ping me

**Comment by kachkaev** [comment]
Has anyone seen a next.js example with nested providers? I'm about to make a pretty content-heavy website with multiple pages and I don't want to load all locale data at start – that's too inefficient. It feels like multiple `<IntlProvider>` instances can be a solution, but it's unclear how to dynamically request multiple locale contexts in next.js. Another i18n library called [i18next](https://github.com/i18next/react-i18next) has a better support of translation namespacing, but it's not using ICU message format, which scares me off 😅 

Any help with pointing to a multi-provider react-intl+next.js example would be great!

**Comment by szimek** [comment]
@ericf It's been over 2 years since your comment, so a lot of things might have changed since then, but I was wondering - how do you prepare these translations per component/applet? I understand that I can use nested `<IntlProvider>`, but the problem is that I'm getting a single JSON file per language from our translation system (Transifex) and I don't know how to extract and import in a component just the part used by this component (and maybe its children as well).

**Comment by Rehan712** [comment]
@ericf how can we use component level intl providers in server side rendered components

**Comment by hjylewis** [comment]
Hi all! ✌️

I was running into a similar issue and came up with a [solution](https://github.com/hjylewis/babel-plugin-inline-i18n-messages) that inlines your localized messages so that it's coupled with your code and easy to code-split (think CSS-in-JS for i18n messages). See [this](https://github.com/hjylewis/babel-plugin-inline-i18n-messages#Motivation) for more info on the motivation for it.

Check it out here: [babel-plugin-inline-i18n-messages](https://github.com/hjylewis/babel-plugin-inline-i18n-messages)

It plays very nicely with `react-intl`. [Here's an example](https://github.com/hjylewis/babel-plugin-inline-i18n-messages/tree/master/examples/react-intl)

I'd appreciate you all checking it out and letting me know if it solves your splitting issues 🙇 

cc @slorber @kachkaev @szimek @Rehan712 @ericf
