### ISSUE TITLE
Splitting messages into smaller chunks

### ISSUE THREAD

**Issue by gpbl** [yahoo/react-intl#76]
Similarly as with the [dojo toolkit i18n](https://dojotoolkit.org/documentation/tutorials/1.7/i18n/) I'd like to split components messages into single files.

- It would help developers to care about their own components and localizations. 
- Translators would also receive smaller, organized files.
- A build script could easily identify the missing messages.
- A language could be chosen a fallback for missing translations (only for [brave people](https://github.com/yahoo/react-intl/issues/35) :-).

For example having two components, `<Alien/>` and `<Earthling/>`, a directory structure would be:

```
└── components
    ├── Earthling.jsx
    ├── Alien.jsx
    └── nls
        ├── en
        │   ├── Earthling.js
        │   └── Alien.js
        ├── es
        │   ├── Earthling.js
        │   └── Alien.js
        └── it
            ├── Earthling.js
            └── Alien.js
```
```js
// nls/en/Earthling.js
{
    'greetings': 'Hello, Earth!'
}
// nls/en/Alien.js
{
    'greetings': 'Hello, Saturn!'
}
```

In a dev or a server-side environment, the components would `require` the localized module from the proper `nls` folder, using it as default `prop.messages` for the `IntlMixin` (not clear yet how, maybe with a static method?).

On the client, only in production, the components should instead consume a unique, big module for each language – that needs to be available before rendering the app. A build script, e.g. webpack, would recognize the `require`s pointing to a `nls` folder and produce such files, for example:

```js
// built en.js
{ 
  messages: {
    'Earthling': {
        'greetings': 'Hello, Earth!',
    },
    'Alien': {
        'greetings': 'Hello, Saturn!'
    }
 }
}
// built es.js
{ 
  messages: {
    'Earthling': {
        'greetings': '¡Hola, Tierra!',
    },
    'Alien': {
        'greetings': '¡Hola, Saturno!'
    }
 }
}
// built it.js
{ 
  messages: {
    'Earthling': {
        'greetings': 'Ciao, Terra!',
    },
    'Alien': {
        'greetings': 'Ciao, Saturno!'
    }
 }
}
```

Clearly this need to change the way the component is getting the message: `this.getIntlMessage('greetings')` vs. `this.getIntlMessage('Earthling.greetings')` (in the compiled version).

I'd like to know how do other developers deal with the problem? Is this something react-intl should help us to achieve? Or I am overcomplicating the solution? :0

**Comment by caridy** [comment]
@gpbl I think you're in the right track, let me give you few more hints:

## pass messages in one go

I will not recommend to organize your translations per react component, this is proven to be a refactor hazard. keep in mind that translations are normally re-use after a refactor, plus, professional translators should not be exposed to the implementation details and component organization, we recommend to organize them in logical groups that can tell translators where to look.

whatever organization you use for your translations (even if you decide to go with a very granular or a giant flat file with all translations), you should be able to pipe that thru the entire app:

```
render: function () {
    <MyApp messages={computedMessagesPerLocale[currentLocale]} locales={[currentLocale, fallbackLocale]}></App>
}
```

## on the server

you can simply have a middleware to compute the currentLocale, and to require all language files (organized) in namespace if needed, and this is a one time operation per locale, not a big deal, essentially, based on the previous example, `computedMessagesPerLocale` should hold that information, including any fallback mechanism (computing missing entries, etc).

## on the client

load a bundle with all locale (this is equivalent to `computedMessagesPerLocale[currentLocale]` and in fact can be computed once for server and client), then just pass that data into the app initialization. we do not recommend to have fallback for messages because that means you have to load 2 or more bundles, instead, rely on a build process to solve inconsistencies between language files, and apply completion on those that are missing or incomplete.

**Comment by gpbl** [comment]
Thanks @caridy for sharing your experience, you are right on everything :-) (I'm also against the fallbacks) I'll follow you ideas and keep this issue updated with my progress, in case someone else is interested.

**Comment by gpbl** [comment]
So after working for a while with react-intl, this isn't actually an issue anymore. A related discussion is https://github.com/yahoo/react-intl/issues/89.

**Comment by hjylewis** [comment]
Hi all! ✌️

I was running into a similar issue and came up with a [solution](https://github.com/hjylewis/babel-plugin-inline-i18n-messages) that inlines your localized messages so that it's coupled with your code and easy to split into smaller bundles (think CSS-in-JS for i18n messages). See [this](https://github.com/hjylewis/babel-plugin-inline-i18n-messages#Motivation) for more info on the motivation for it.

Check it out here: [babel-plugin-inline-i18n-messages](https://github.com/hjylewis/babel-plugin-inline-i18n-messages)

This idea would it would inline the messages like this:
```javascript
<FormattedMessage id="key.path.hello" />
<FormattedMessage id="key.path.sup" />

      ↓ ↓ ↓ ↓ ↓ ↓

import { addMessages } from "i18n/addMessages.js";
addMessages([
  ["key.path.hello", "hello, world"],
  ["key.path.sup", "sup, world"],
]);
<FormattedMessage id="key.path.hello" />
<FormattedMessage id="key.path.sup" />
```

It plays very nicely with `react-intl`. [Here's an example](https://github.com/hjylewis/babel-plugin-inline-i18n-messages/tree/master/examples/react-intl)

I'd appreciate you all checking it out and letting me know if it solves your splitting issues 🙇 

cc @gpbl @caridy
