### ISSUE TITLE
Implementing several languages

### ISSUE THREAD

**Issue by SBRK** [yahoo/react-intl#81]
Since the example only has one language (which I find odd, since the purpose of react-intl is to handle several languages), I'm not sure what the best practice is for implementing several languages. 
Initially I thought react-intl would handle the language to choose from the locales we pass, then use the corresponding messages, but since we pass only one set of messages, what is the use of passing several locales ? Is it the responsibility of the developer to detect the user locale and to pass the corresponding messages ?

**Comment by adibsaad** [comment]
I started using this recently and from what I can tell, it seems most people ideally would like something like this

  ```
  var intlData = {
    ...
    messages: {
      'some_pane': {
        'some_msg': {
          'en-US': 'US english',
          'en-GB': 'British english'
        }
      }
    }
  };
  ```

but the problem is that if a user only needs 1 or 2 languages, say english and spanish, then it would be inefficient to send all languages (remember: this is client-side). I'm guessing the way most people do it is store the user's preferences in a cookie or something, then call React's store to get the localisation from the server, and you package each one on its own

```
  var intlData = {
    locales: 'en',
    messages: {
      'some_pane': {
        'some_msg': 'english message'
      }
    }
  };
```

then when a user selects a different language, update ```intlData``` to be

```
var intlData = {
    locales: 'es',
    messages: {
      'some_pane': {
        'some_msg': 'spanish message'
      }
    }
  };
```

then update all your components and/or reload the app. Again, I'm new to react-intl, so if I'm wrong, someone please correct me ;)

**Comment by caridy** [comment]
@adibsaad you're correct. We are not opinionated how you handle your messages, and out position is: do what you think is best to pass the right messages into the component, whether you use the mixin or you do your own thing, it doesn't really matter.

as you mentioned, we DO NOT recommend passing all language information (translations) because in complex apps this might be big, but if that's not a problem for you, then go for it :).

BTW, there are few issues that touch on this, just search for them in this repo.

**Comment by slorber** [comment]
@caridy, still it's not clear what's the behavior of react-intl when we pass something like that:

```
var intlData = {
    locales: ['es','fr','en','dk'],
    messages: {
      'some_pane': {
        'some_msg': 'spanish message'
      }
    }
};
```

I guess knowing the locale is an useful information for date/currency formatting inside messages and stuff like that, but it is just unclear what the effect would be if you provide an array of locales.

In the above example, I don't know at all according to which locale the dates will be formatted.
My first guess is that locale specific formatting is not necessarily defined for each locale and thus we can eventually provide "fallbacks" but it's the only thing I can imagine and it does not seem to be documented anywhere while 


In https://github.com/yahoo/intl-messageformat

> locales - {String | String[]} - A string with a BCP 47 language tag, or an array of such strings. If you 
> do not provide a locale, the default locale will be used, but you should always provide one!

We don't know anything of how this array of locale will be used. We can only guess :(

**Comment by caridy** [comment]
> I guess knowing the locale is an useful information for date/currency formatting inside messages and stuff like that

that is correct, it is just propagated down to the browser's low-level Intl implementation, and the way the primitives will use the locales array is described here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_identification_and_negotiation

If you use `locales = ['fr-CA']`, it will try to figure what's the best fit, which could be `fr-CA`, or `fr` or your browser's default locale, which for me is `en`. The best match will be used to format the data and the message.

**Comment by ericf** [comment]
@SBRK put simply: React Intl is about internationalization, not localization. Localizing your content is up to you since its specific to your app; i.e. translated strings.
