### ISSUE TITLE
Accessing locale in component

### ISSUE THREAD

**Issue by mg** [yahoo/react-intl#83]
Hi, 

Im adding the IntlMixin to the App component, and <FormattedNumber> elements in child components are picking up the correct locale. But now I need to use the Intl.NumberFormat function and was wondering if I have access the locale in the component that <FormattedNumber> is using?

**Comment by caridy** [comment]
Yes, any component using the mixin will be able to do `this.context.locales`, which the mixin will provision based on a hierarchical lookup.

I'm curious, why do you need to use `Intl.NumberFormat` directly? Why not using the `this.formatNumber()` which is provided by the mixin? The main difference here is the caching mechanism provided by the mixin since creating instances of `Intl.NumberFormat()` is a very very expensive operation.

**Comment by mg** [comment]
Alright I will use that. But the documentation kind of says that we shouldn't use it since it will be removed in the future.

Thanks!

ps. Is there any way to see a list of supported locales? 'is-IS' seems to be unsupported.

**Comment by caridy** [comment]
we extract the locales from the cldr project. ir they dont support that, you can open a ticket to follow up with them.

as for deprecation. we are not sure yet, but we will always provide an alternative inperative api with cache support under the hood. dont worry about that.

**Comment by ericf** [comment]
@mg You're right, the mixin's methods are legacy and not the happy path. Instead of using those, @caridy should have suggested that you use the [`<FormattedNumber>` component](http://formatjs.io/react/#formatted-number).

**Comment by ericf** [comment]
@mg `is-IS` will be supported in the next feature release, `v1.2.0`.
