### ISSUE TITLE
How to define defaultLocale?

### ISSUE THREAD

**Issue by pedroteixeira** [yahoo/react-intl#85]
Is there any way to define a global default locale different than english?

Using browserify (runtime = browser), I'm doing something like this:
```
var ReactIntl = require('react-intl');
window.ReactIntl = ReactIntl;
require('react-intl/dist/locale-data/br');
```

Any way to import react-intl without the added en locale? I'm guessing that would make 'br' default?

**Comment by caridy** [comment]
No, the library has english built-in, that was a conscientiousness decision to simplify the default behavior and fallback. What you're doing is just find, it will add only few more bytes to payload since the locale data is very very small when gzipped.

Is there any other reason, other than the size of the payload, that you want to discuss?

Unfortunately, even if br locale was the default locale, you will still need to specify it when creating instances since that value is propagated to the primitives (Intl.NumberFormat, Intl.DateTimeFormat constructors), which will fall to the system default locale if no locale is specified. In other words, you should ALWAYS pass at least one locale, otherwise the results might be unexpected for some users.

**Comment by pedroteixeira** [comment]
So, there is really *no way* to redefine the defaultLocale to 'br'?
No patch? No runtime settings in the browser?

thanks for clarifying.

**Comment by pedroteixeira** [comment]
Realized that IntlMixin uses React context as way to propagate downwards.. It's sufficient indeed :)

**Comment by caridy** [comment]
Yeah, you only have to define it as props at the very top level, with IntlMixin applied to the top level component, or you set it as context directly at the top level, and that will guarantee that all components in the app will have access to it. That also includes `messages` and `formats` in case you need to use them as well.

**Comment by ericf** [comment]
The fact that the IntlMixin propagates the `locales` value down to child components, allowed us to avoid the mess of having `ReactIntl` implement a static method to update the `defaultLocale` values of its dependencies: `IntlMessageFormat` and `IntlRelativeFormat`. Doing that would have side-effects, so we'd rather be explicit.
