### ISSUE TITLE
Question: React and Redux : Use Locale data loaded into store from server on client?

### ISSUE THREAD

**Issue by sandeepdude** [yahoo/react-intl#871]
Hi,

Our project requires a few component to be rendered on the server side and other components to be rendered on the client side. We are using Redux in our project.

We send the translated messages in the initial state of the store from the server side and use in the client. Is it possible to set the locale data also in the same way?

Below is the flow we are trying to achieve:

**On Server Side:**
1) Render Component1 on the server side.
2) Send Locale data and translated messages in the initial state of the store from server side.

**On Client Side:**
1) Get the translations and locale data from the redux store
2) use react-intl's **addLocaleData()** to set the locale data retrieved from the store.
3) Render component2 and component3

**Comment by ericf** [comment]
Yes, and you probably also want to include the `initialNow` value passed to `<IntlProvider>` on the server so that the client can start with the same "now" time when rendering relative dates.

You can see this example for Next.js which does a similar server + client rendering https://github.com/zeit/next.js/tree/master/examples/with-react-intl
