### ISSUE TITLE
Using a key instead of a string for FormattedMessage id prop

### ISSUE THREAD

**Issue by jmcrthrs** [yahoo/react-intl#877]
I am considering using the below format for referencing translation strings. 

This object is passed to IntlProvider:

```
// en.js
const en = {
  cancel: 'Cancel',
};
```

I import the same object wherever I require a translation, and use the key for the FormattedMessage id

```

<import translationKeys from '../../translations/en.js';

...

<FormattedMessage id={translationKeys.cancel} /></label>
```

I'm interested how performance will be affected versus just using a string for id.

**Comment by ericf** [comment]
It won't in this case since the `id` is `'cancel'` (lowercase) while the value you're passing to the `id` prop is `'Cancel'` (capitalized).

You'll want to provide the correct `id`. You might be interested in the Babel plugin which helps extract the messages defined in your source code: https://github.com/yahoo/babel-plugin-react-intl
