### ISSUE TITLE
intlProvider.getChildContext() is undefined

### ISSUE THREAD

**Issue by kjudd** [yahoo/react-intl#944]
Hi, I am trying to write a jest test for a react-intl component using enzyme. 

I took the enzyme helper function verbatim from the docs https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#dom-rendering and imported it into my test. 

When I try to import shallowWithIntl from the helper function file, I get the error:
` TypeError: Cannot read property 'intl' of undefined`
coming from the helper file.

When I try to log:
const intlProvider = new IntlProvider({ locale: 'en' }, {});
console.log(intlProvider.getChildContext())
const { intl } = intlProvider.getChildContext()

intlProvider.getChildContext() is undefined. 

Am I using this helper function correctly? I haven't modified it from what is in the docs. The jest mock helper function is working correctly, but tests for components using injectIntl are failing without the enzyme helper.

Thanks.

**Comment by aperkaz** [comment]
Hello, how did you solve it @kjudd ? I am facing the same issue.
Thanks :slightly_smiling_face:

**Comment by allienx** [comment]
I ran into this issue because I had a Jest mock as outlined [here](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#jest-mock). Removing the mock for `react-intl` fixed this issue. 

Also, you can't just comment out the contents of `__mocks__/react-intl.js`, you have to remove (or rename) the file.
