### ISSUE TITLE
Problems when using `this.props.children`

### ISSUE THREAD

**Issue by wmartins** [yahoo/react-intl#97]
Hi, I was trying to add some dynamic children using `this.props.children`, but, when I do that, I can't make it work.

Here is the demo without using `this.props.children`: http://jsfiddle.net/9v7hn4yw/1/
Here is the demo using `this.props.children`: http://jsfiddle.net/kqn7do6t/1/

In the demo using `this.props.chilren` I get `Couldn't find Intl message: hello`.

I've added some logging info about `props` and `context` to try to figure out what's going on, and it appears that `this.context` object when using `this.props.children` is not correct.

Here are the fiddles:

http://jsfiddle.net/9v7hn4yw/2/
http://jsfiddle.net/kqn7do6t/2/

Am I doing something wrong? Are there any examples using `this.props.children`?

What do you think about it? Thank you!

**Comment by ericf** [comment]
@wmartins I ran the examples using React 0.13.1, and I was able to find out what's going on as there are now warnings for this:

```
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (messages) while mounting PersonInfo (see: http://fb.me/react-context-by-parent)
```

Following <http://fb.me/react-context-by-parent>, I found out some details on what's going on. In React < 0.14 (not released yet), context is owner-based instead of parent-based, and in the following code `<PersonInfo>` does not have an owner since the component instance created _outside_ another React component:

```jsx
React.render(
    <App {...i18n['pt-BR']}>
        <PersonInfo name="William" />
    </App>,
    document.body
);
```

The good news is that in React 0.14+, the code you have here will work as you expected because in the parent-based context world, `<PersonInfo>` does have a parent, `<App>` and it uses the `IntlMixin` so the context will be propagated.

The problem you're current experiencing is not a problem with the use `this.props.children`, it's that you're hitting the edge case where `<PersonInfo>` has no owner since its created at the top-level and not inside another React component's `render()` method.

You can find out more about this change from owner-based to parent-based context in the following links:
- https://github.com/facebook/react/issues/2112
- https://github.com/facebook/react/issues/3451#issuecomment-83000311

Hope that helps!

**Comment by wmartins** [comment]
Thank you @ericf!

**Comment by alansouzati** [comment]
Hi, 

  While the new version of react is not released, I believe I've found a work around for this. In my top-level(root) component, I've cloned the `this.props.children` and injected the `react-intl` props. With that, I don't need to set the i18n props for each of my children. In the future, refactoring will be easier because there is only one location for change (hopefully :smile:). Hope it helps...

I know that clone operations are expensive, but I believe this could work as an interim solution.

```javascript
var React = require('react');
var ReactIntl = require('react-intl');
var IntlMixin = ReactIntl.IntlMixin;

var App = React.createClass({

  mixins: [IntlMixin],

  propTypes: {
    centered: React.PropTypes.bool,
  },

  getDefaultProps: function () {
    return {
      centered: true,
      locales: 'en-US',
      messages: require('../messages/en-US')
    };
  },

  render: function() {
    var classes = ["app"];
    if (this.props.centered) {
      classes.push("app--centered");
    }
    if (this.props.inline) {
      classes.push("app--inline");
    }
    if (this.props.className) {
      classes.push(this.props.className);
    }

    //remove this when React 0.14 is released. This is required because context props are not propagated.
    var bodyComponent = React.Children.map(this.props.children, function(child) {
      return React.cloneElement(child, {
        locales: this.props.locales,
        messages: this.props.messages
      });
    }.bind(this));

    return (
      <div className={classes.join(' ')}>
        {bodyComponent}
      </div>
    );
  }
});

module.exports = App;
```

**Comment by wmartins** [comment]
@alansouzati, I had to do something like that to make it work too. Thanks for sharing!

And waiting for React 0.14 to be released hahaha :muscle:!
