### ISSUE TITLE
How to use IntlProvider using Enzyme? The `messages` exploid the snapshots.

### ISSUE THREAD

**Issue by dennisat** [yahoo/react-intl#973]
This is not a... bug. It is something expected. But at the end the snapshots are looking awful exploded from the message object are completely unmaintenable.

In tests you have to wrap the tested component with `IntlProvider` and/or pass the `intl` object. `Enzyme`'s `mount` renderer extracts the content of the `messages` object. 

A cheat is to extract for the snapshot the `children()` but nested `intl`s `messages` exploided again.

Which is the best practice to test components with `enzyme` and `intl`?

**Comment by okovpashko** [comment]
@dennisat maybe you meant `shallow` renderer? `Mount` renderer gives just HTML in snapshots without any React component properties.

**Comment by dennisat** [comment]
@okovpashko thanks for your reply, the `mount` of `enzyme` renders and the invisible components and the values of props of them. The `renderer` of `react-test-renderer` is doing what you wrote and this is what finally I am doing, but I miss the `enyzme`!

**Comment by okovpashko** [comment]
@dennisat are you sure about `mount`? According to the documentation, it performs full DOM rendering, while `shallow` renders only top level component and tags for child components along with their props.
We also have Intl appeared in props in some snapshots but we don't set messages in tests for Intl thus we don't have failed tests because of changed messages.

**Comment by dennisat** [comment]
No, I am with you. The key is what you said, we should not provide messages for the tests! The default message will be used.
