### ISSUE TITLE
Day minus 1 using intl in Safari

### ISSUE THREAD

**Issue by lauterry** [yahoo/react-intl#991]
Hello

I expect the following code 
```
this.props.intl.formatDate(new Date(1972, 5, 15), {day: "2-digit", month: "long", year: "numeric"})
```
to output

```15 juin 1972```.

However it outputs ```14 juin 1972```.

The day is not correct.

This issue has occurred on Safari browser mobile and desktop.

This issue also occurred for Chrome when the date is <  march 31th 1970

I'm using react-intl 2.2.3 and intl 1.1.0

Best regards

**Comment by sfaxino** [comment]
I have the same issue with `Safari` for `21 March 2000`

**Comment by sfaxino** [comment]
it turns out to be a safari issue. 

from the console:

`Safari`:
```
Date.parse('March 21, 2000');
953622000000
```

`Chrome`
```
Date.parse('March 21, 2000');
953625600000
```

**Comment by ghostd** [comment]
You could:
* parse an ISO string to get your date browser compliant (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse): A string representing an RFC2822 or (a variant of) ISO 8601 date (other formats may be used, but results may be unexpected))
* or use a lib to parse your date (date-fns or moment)

**Comment by sfaxino** [comment]
The thing is I'm trying to avoid using any lib for this.

The other thing, I'm actually trying to create a new Date by only providing the Month and Day only.

On Safari, 
- `Date.parse('March 21')`  gives `953622000000` which is wrong and because it sets the year to `2000`. 
- `new Date('March 21')` gives `Tue Mar 21 2000 00:00:00 GMT-0700 (PDT)`

On Chrome, 
- `Date.parse('March 21')` gives `985161600000`
- `new Date('March 21')` gives `Wed Mar 21 2001 00:00:00 GMT-0800 (PST)`

But you might say, oh wait on chrome, `2001` is not a leap year and can cause some issues. 
the good news, chrome is smart enough to handle that scenario:

 `new Date('Feburary 29')` gives `Thu Mar 01 2001 00:00:00 GMT-0800 (PST)`

**Comment by sfaxino** [comment]
oh wait, just noticed something, 

on Safari, `new Date('March 21')` actually gives the correct value.

but 
```
intl.formatDate(new Date('March 21'),  {
    month: 'long',
    day: 'numeric'
  })
```
gives the wrong value 
`March 20`

I guess this is a `react-intl` bug.

**Comment by sfaxino** [comment]
## To sum up: 

**Safari** bug: 

`Date.parse('March 21, 2000')`
==> `953622000000`


**react-intl** bug

```
intl.formatDate(new Date('March 21'),  {
    month: 'long',
    day: 'numeric'
  })
```
==> `March 20`

**Comment by ghostd** [comment]
Can you try this:
```
new Intl.DateTimeFormat('en-US', {
    month: 'long',
    day: 'numeric'
  }).format(Date.parse('March 21, 2000'));
```

I think it is not a react-intl bug. react-intl uses the [Intl API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl). Two possibilities:
- you found a bug in the Intl implementation of Safari
- you found a bug in the [intl.js polyfill](https://github.com/andyearnshaw/Intl.js/) (check if you load it)

**Comment by papasmile** [comment]
Looks like it's Safari again. I ran @ghostd's snippet in JSFiddle: FF gives March 21 while Safari gives March 20!

**Comment by sfaxino** [comment]
Yea sounds like it's Safari. thanks @ghostd and @papasmile

**Comment by okuryu** [comment]
@ghostd @papasmile Thanks a lot for your helps! closing..
