### ISSUE TITLE
React 16 String Returns

### ISSUE THREAD

**Issue by nathanforce** [yahoo/react-intl#999]
With React 16 comes the ability for components to directly return strings.

What are your thoughts on having react-intl support unwrapped messages?  Should it become the default, which would introduce a lot of breaking changes, or is it too late for such a change?  Given the current option to pass a render function as a child to `Formatted*` components, a `StringFormatted*` abstraction would be fairly straightforward.

https://codesandbox.io/s/8q6Go6Bv5

Here's a simple demo of the StringFormatted approach.  If we like the idea I'd be happy to contribute a PR once React 16 is released.

**Comment by bsr203** [comment]
This is useful for cases like internationalizing texts on select box (options). Now I get error

```
console.error node_modules/fbjs/lib/warning.js:33
      Warning: validateDOMNesting(...): <span> cannot appear as a child of <option>.
          in span (created by FormattedMessage)
```

**Comment by nathanforce** [comment]
@bsr203 This is already supported today using the `tagName` property on `FormattedMessage`.

```js
          <FormattedMessage tagName="option" id="myMessage" />
```

**Comment by bsr203** [comment]
thanks @nathanforce unfortunately, FormatMessage doesn't pass rest of the props, so I couldn't pass the 'value' attribute to option. Using the workaround in https://github.com/yahoo/react-intl/issues/286 did the trick. thanks.

**Comment by Ephys** [comment]
if you want that behavior now, you can configure your `IntlProvider` component like this:

```javascript
import { IntlProvider } from 'react-intl';

function Fragment(props) {
  return props.children;
}

export default function App(props) {
  return (
    <IntlProvider node={Fragment}>
      {props.children}
    </IntlProvider>
  );
}
```

Or define your own set of `Formatted*` components like this:

```javascript
import { FormattedMessage as IntlFormattedMessage } from 'react-intl';

function noop(msg) {
  return msg;
}

export function FormattedMessage(props) {
  return <IntlFormattedMessage {...props} children={noop} />;
}
```

**Comment by donysukardi** [comment]
This is awesome, @Ephys! Why didn't I think of that? 👍

**Comment by bensampaio** [comment]
@Ephys that's a good work around for now, but wouldn't it make more sense for this to be the default?

**Comment by steida** [comment]
Nice to see my humble textComponent API suggestion is so useful.

**Comment by hudochenkov** [comment]
Thank you, @Ephys. Very good solution.

Here is an improvement to support `FormattedHTMLMessage`. `FormattedHTMLMessage` doesn't have `children`.

```js
import { IntlProvider } from 'react-intl';

function Fragment(props) {
  return props.children || <span {...props} /> || null;
}

export default function App(props) {
  return (
    <IntlProvider textComponent={Fragment}>
      {props.children}
    </IntlProvider>
  );
}
```

With the code above we can use `FormattedMessage` in places, where we couldn't because of `<span>` added to a message:

```jsx
<select>
  <option><FormattedMessage id="message-id" /></option>
</select>
```

But we still can't use `FormattedMessage` for attributes. This won't work:

```jsx
<abbr title={<FormattedMessage id="message-id" />}>
  HTML
</abbr>
```

**Comment by bensampaio** [comment]
@redonkulus would it be possible to also add this breaking change to the v3 release as well? I mean, using `Fragment` as default instead of `span`.

**Comment by redonkulus** [comment]
@bensampaio interesting suggestion, I'm not opposed to it, but it could potentially break a lot of apps that are counting on the `<span />` for styling, snapshot testing and other use cases. The [workaround](https://github.com/formatjs/react-intl/issues/999#issuecomment-335799491) suggested seems like it gives users that support if they need it. 

I'm interested to hear from @DragonRaider5 and others on their thoughts.

**Comment by DragonRaider5** [comment]
I'm also not sure about it - I think if somebody really just wants the string they might as well use the FAC pattern?
I think what would be more beneficial is allowing for components in the `tagName` prop.

However - besides breaking a lot of old code - I don't see an issue in swapping to `React.Fragment` either.

By the way: I didn't test this, but one should already be able to use fragments as default via the `textComponent` prop on the `IntlProvider`:
```js
import React, { Fragment } from 'react'
import { IntlProvider } from 'react-intl'

import withMessages from './container's

const Provider = withMesages(IntlProvider)
Provider.defaultProps = {
  textComponent: Fragment
}

export default Provider
```

Question is: Do we want to make this the default.

**Comment by bensampaio** [comment]
@redonkulus and @DragonRaider5 I suggest changing this because, if I am not wrong, the span solution is there because when this lib was created it was not possible to return a string or fragment from a component. At the moment, the spans add a lot of clutter and in most cases serve no purpose.
Specially because the `<Formatted*` components do not accept a className (or did that change?).

As mentioned in this issue, it is of course possible to configure the `tagName`. That's actually what I have been doing for a long time. I am just wondering if the default shouldn't be `Fragment` since both in react and react-native I keep finding code like this:

react
```
<span className={styles.myClass}>
  <FormattedMessage {...translations.myTranslation} />
</span>
```

react-native
```
<Text style={styles.myClass}>
  <FormattedMessage {...translations.myTranslation} />
</Text>
```

In the end, if the tagName is not configured, this always results in duplicate `span`s or `Text`s since styles are necessary.

@DragonRaider5 what do you mean with the FAC pattern? Btw I do like your suggestion, but this lib has more components than just `FormattedMessage`. You would need to wrap each one of them with a function, in that case I rather configure the `tagName`.

Anyway if you say this is a big change and will bring lots of headaches then I am also fine leaving it as it is.

**Comment by DragonRaider5** [comment]
@bensampaio you're right about the `className` and I'm rly wondering why nothing is being passed. @redonkulus what do you think about this, should we change it? That's quite ridiculous in my opinion...

FAC stands for function-as-child, e.g.
```js
import { FormattedMessage } from 'react-intl'
import messages from './messages'

export default () => (
  <FormattedMessage {...messages.message}>
    { (nodes) => console.log(nodes) || null }
  </FormattedMessage>
)
```

My suggestion was meant for the library itself, not to make the user implement this in every one of their projects.
I had this in mind to allow for a clear separation between components and "string returners", which would prevent breaking old stuff while also providing a new API.
With the proposed API code would look like this:
```js
import { t } from 'react-intl'
import messages from './messages'

export default () => (
  <div className='my-div'>
    { t(messages.message) }
  </div>
)
```

However the same can already be achieved using `injectIntl` (might break JSX in `values`):
```js
import { injectIntl } from 'react-intl`
import messages from './messages'

export default injectIntl(({ intl: formatMessage }) => (
  <div className='my-div'>
    { formatMessage(messages.message) }
  </div>
)
```

@redonkulus
To me the consideration is: should `<Formatted* />` feel like components in a way that they add to the DOM or is this a stubborn and out-of-date view?
I feel like if you want a string you should use injectIntl or some other pattern.
However I can also see the point in removing all those (mostly useless) `span`s...

Maybe we should introduce `<Message />`, `<Relative />` etc., which don't format because they don't add any styling information?

In case we decide to just change the default to `React.Fragment` I think we can just provide a link to an upgrade guide and safe people a lot of trouble, making the change not as bad.
